language: ruby
rvm:
    - 2.1.1
bundler_args: --without development:production
before_install:
    - gem update bundler
script:
    - RAILS_ENV=test bundle exec rake db:setup
    - RAILS_ENV=test bundle exec rake spec 
